DS-419: FOR TESTING PURPOSES, remove version check

diff --git a/.github/workflows/release_new_version.yaml b/.github/workflows/release_new_version.yaml
--- a/.github/workflows/release_new_version.yaml
+++ b/.github/workflows/release_new_version.yaml
@@ -18,8 +18,8 @@ jobs:
   publish:
     name: Publish library to NPM
     runs-on: ubuntu-24.04
-    outputs:
-      set-as-latest: ${{ steps.check_latest.outputs.is-latest }}
+    # outputs:
+    #   set-as-latest: ${{ steps.check_latest.outputs.is-latest }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -32,42 +32,42 @@ jobs:
           registry-url: https://registry.npmjs.org/
       - name: Copy root README.md to library
         run: cp README.md core/README.md
-      - name: Check for latest version
-        id: check_latest
-        run: |
-          LATEST_RELEASE=$(curl -L \
-            -H "Authorization: Bearer ${{ github.token }}" \
-            https://api.github.com/repos/${{ github.repository }}/releases/latest \
-            | jq -r '.tag_name')
+      # - name: Check for latest version
+      #   id: check_latest
+      #   run: |
+      #     LATEST_RELEASE=$(curl -L \
+      #       -H "Authorization: Bearer ${{ github.token }}" \
+      #       https://api.github.com/repos/${{ github.repository }}/releases/latest \
+      #       | jq -r '.tag_name')
 
-          CURRENT_VERSION=$(echo "${{ github.event.release.tag_name }}" | cut -c2-)
+      #     CURRENT_VERSION=$(echo "${{ github.event.release.tag_name }}" | cut -c2-)
 
-          if [[ "${LATEST_RELEASE}" == "${{ github.event.release.tag_name }}" ]]; then
-            if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-              echo "is-latest=true" >> "$GITHUB_OUTPUT"
-            else
-              echo "::error::When publishing a latest release, the version has to respect the major.minor.patch-format."
-              exit 1
-            fi
-          else
-            echo "is-latest=false" >> "$GITHUB_OUTPUT"
-            if ${{ github.event.release.prerelease }}; then
-              echo "NPM_TAG=prerelease" >> $GITHUB_ENV
-            else
-              echo "NPM_TAG=patch" >> $GITHUB_ENV
-            fi
-          fi
+      #     if [[ "${LATEST_RELEASE}" == "${{ github.event.release.tag_name }}" ]]; then
+      #       if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      #         echo "is-latest=true" >> "$GITHUB_OUTPUT"
+      #       else
+      #         echo "::error::When publishing a latest release, the version has to respect the major.minor.patch-format."
+      #         exit 1
+      #       fi
+      #     else
+      #       echo "is-latest=false" >> "$GITHUB_OUTPUT"
+      #       if ${{ github.event.release.prerelease }}; then
+      #         echo "NPM_TAG=prerelease" >> $GITHUB_ENV
+      #       else
+      #         echo "NPM_TAG=patch" >> $GITHUB_ENV
+      #       fi
+      #     fi
       - name: Build fudis-core
         run: npm run build:dist
         working-directory: core
       - name: Publish latest
-        if: steps.check_latest.outputs.is-latest == 'true'
+        # if: steps.check_latest.outputs.is-latest == 'true'
         run: npm publish --loglevel verbose --access public
         working-directory: core/dist
-      - name: Publish patch or pre-release
-        if: steps.check_latest.outputs.is-latest == 'false'
-        run: npm publish --access public --tag ${{ env.NPM_TAG }}
-        working-directory: core/dist
+      # - name: Publish patch or pre-release
+      #   if: steps.check_latest.outputs.is-latest == 'false'
+      #   run: npm publish --access public --tag ${{ env.NPM_TAG }}
+      #   working-directory: core/dist
 
   # publish-docs:
   #   name: Publish docs to AWS
