DS-419: Restore workflow for its previous glory (the issue was trusted publisher organization config with unnecessary at sign)

diff --git a/.github/workflows/release_new_version.yaml b/.github/workflows/release_new_version.yaml
--- a/.github/workflows/release_new_version.yaml
+++ b/.github/workflows/release_new_version.yaml
@@ -1,13 +1,10 @@
 name: Release new version
 
 on:
-  push:
-    branches:
-      - "DS-419-workflow-fixes"
-  # release:
-  #   types:
-  #     - released
-  #     - prereleased
+  release:
+    types:
+      - released
+      - prereleased
 
 permissions:
   # Permission to generate OIDC token
@@ -18,8 +15,8 @@ jobs:
   publish:
     name: Publish library to NPM
     runs-on: ubuntu-24.04
-    # outputs:
-    #   set-as-latest: ${{ steps.check_latest.outputs.is-latest }}
+    outputs:
+      set-as-latest: ${{ steps.check_latest.outputs.is-latest }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -30,88 +27,86 @@ jobs:
           node-version-file: .nvmrc
           # Specifying `registry-url` triggers `setup-node` to setup NPM authentication.
           registry-url: https://registry.npmjs.org/
-          scope: funidata
       - name: Copy root README.md to library
         run: cp README.md core/README.md
-      # - name: Check for latest version
-      #   id: check_latest
-      #   run: |
-      #     LATEST_RELEASE=$(curl -L \
-      #       -H "Authorization: Bearer ${{ github.token }}" \
-      #       https://api.github.com/repos/${{ github.repository }}/releases/latest \
-      #       | jq -r '.tag_name')
+      - name: Check for latest version
+        id: check_latest
+        run: |
+          LATEST_RELEASE=$(curl -L \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            https://api.github.com/repos/${{ github.repository }}/releases/latest \
+            | jq -r '.tag_name')
 
-      #     CURRENT_VERSION=$(echo "${{ github.event.release.tag_name }}" | cut -c2-)
+          CURRENT_VERSION=$(echo "${{ github.event.release.tag_name }}" | cut -c2-)
 
-      #     if [[ "${LATEST_RELEASE}" == "${{ github.event.release.tag_name }}" ]]; then
-      #       if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-      #         echo "is-latest=true" >> "$GITHUB_OUTPUT"
-      #       else
-      #         echo "::error::When publishing a latest release, the version has to respect the major.minor.patch-format."
-      #         exit 1
-      #       fi
-      #     else
-      #       echo "is-latest=false" >> "$GITHUB_OUTPUT"
-      #       if ${{ github.event.release.prerelease }}; then
-      #         echo "NPM_TAG=prerelease" >> $GITHUB_ENV
-      #       else
-      #         echo "NPM_TAG=patch" >> $GITHUB_ENV
-      #       fi
-      #     fi
+          if [[ "${LATEST_RELEASE}" == "${{ github.event.release.tag_name }}" ]]; then
+            if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "is-latest=true" >> "$GITHUB_OUTPUT"
+            else
+              echo "::error::When publishing a latest release, the version has to respect the major.minor.patch-format."
+              exit 1
+            fi
+          else
+            echo "is-latest=false" >> "$GITHUB_OUTPUT"
+            if ${{ github.event.release.prerelease }}; then
+              echo "NPM_TAG=prerelease" >> $GITHUB_ENV
+            else
+              echo "NPM_TAG=patch" >> $GITHUB_ENV
+            fi
+          fi
       - name: Build fudis-core
         run: npm run build:dist
         working-directory: core
       - name: Publish latest
-        # if: steps.check_latest.outputs.is-latest == 'true'
-        # actions/setup-node automatically sets a placeholder NODE_AUTH_TOKEN that prevents npm from using OIDC. Explicitly set it to empty string to enable OIDC trusted publishing.
-        run: NODE_AUTH_TOKEN="" npm publish --loglevel verbose --access public --tag next
+        if: steps.check_latest.outputs.is-latest == 'true'
+        run: npm publish --access public
         working-directory: core/dist
-      # - name: Publish patch or pre-release
-      #   if: steps.check_latest.outputs.is-latest == 'false'
-      #   run: npm publish --access public --tag ${{ env.NPM_TAG }}
-      #   working-directory: core/dist
+      - name: Publish patch or pre-release
+        if: steps.check_latest.outputs.is-latest == 'false'
+        run: npm publish --access public --tag ${{ env.NPM_TAG }}
+        working-directory: core/dist
 
-  # publish-docs:
-  #   name: Publish docs to AWS
-  #   runs-on: ubuntu-24.04
-  #   needs:
-  #     - publish
-  #   defaults:
-  #     run:
-  #       working-directory: core
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v6
-  #     - name: Set up Node.js
-  #       uses: actions/setup-node@v6
-  #       with:
-  #         node-version-file: .nvmrc
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-region: ${{ vars.AWS_REGION }}
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #     - name: Parse library version number
-  #       run: echo "VERSION=$(npm pkg get version | jq -r '.[]')" >> "$GITHUB_ENV"
-  #     - name: Install dependencies
-  #       run: npm ci
-  #     - name: Build docs
-  #       run: npm run build:storybook
-  #     - name: Copy docs to S3 bucket
-  #       run: aws s3 sync storybook-static s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/v/$VERSION
-  #     - name: Check for Storybook redirect
-  #       id: check-storybook-redirect
-  #       if: needs.publish.outputs.set-as-latest == 'true'
-  #       run: echo "REDIRECT_STORYBOOK=true" >> $GITHUB_ENV
-  #     - name: Update root redirect to this version
-  #       if: env.REDIRECT_STORYBOOK == 'true'
-  #       run: |
-  #         echo "<html>
-  #         <head>
-  #         <meta http-equiv='refresh' content='0; url=https://fudis.funidata.fi/core/v/$VERSION/index.html' />
-  #         </head>
-  #         </html>" > /tmp/index.html
-  #         aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core --cache-control max-age=5
-  #         aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/index.html --cache-control max-age=5
-  #         aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/v/index.html --cache-control max-age=5
+  publish-docs:
+    name: Publish docs to AWS
+    runs-on: ubuntu-24.04
+    needs:
+      - publish
+    defaults:
+      run:
+        working-directory: core
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+      - name: Set up Node.js
+        uses: actions/setup-node@v6
+        with:
+          node-version-file: .nvmrc
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: Parse library version number
+        run: echo "VERSION=$(npm pkg get version | jq -r '.[]')" >> "$GITHUB_ENV"
+      - name: Install dependencies
+        run: npm ci
+      - name: Build docs
+        run: npm run build:storybook
+      - name: Copy docs to S3 bucket
+        run: aws s3 sync storybook-static s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/v/$VERSION
+      - name: Check for Storybook redirect
+        id: check-storybook-redirect
+        if: needs.publish.outputs.set-as-latest == 'true'
+        run: echo "REDIRECT_STORYBOOK=true" >> $GITHUB_ENV
+      - name: Update root redirect to this version
+        if: env.REDIRECT_STORYBOOK == 'true'
+        run: |
+          echo "<html>
+          <head>
+          <meta http-equiv='refresh' content='0; url=https://fudis.funidata.fi/core/v/$VERSION/index.html' />
+          </head>
+          </html>" > /tmp/index.html
+          aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core --cache-control max-age=5
+          aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/index.html --cache-control max-age=5
+          aws s3 cp /tmp/index.html s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/v/index.html --cache-control max-age=5
