DS-497 add error handling

diff --git a/.github/workflows/release_new_version.yaml b/.github/workflows/release_new_version.yaml
--- a/.github/workflows/release_new_version.yaml
+++ b/.github/workflows/release_new_version.yaml
@@ -34,7 +34,12 @@ jobs:
             | jq -r '.tag_name')
 
           if [[ "${LATEST_RELEASE}" == "${{ github.event.release.tag_name }}" ]]; then
-            echo "is-latest=true" >> "$GITHUB_OUTPUT"
+            if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "is-latest=true" >> "$GITHUB_OUTPUT"
+            else
+              echo "::error::When publishing a latest release, the version has to respect the major.minor.patch-format."
+              exit 1
+            fi
           else
             echo "is-latest=false" >> "$GITHUB_OUTPUT"
             if ${{ github.event.release.prerelease }}; then
